name: build

on:
  push:
    branches: [ master, noetic-devel ] #  when master or noetic-devel branch is pushed to
  pull_request:
    branches: [ master ] # when there is a pull request against master

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
